theme = "catppuccin_frappe"

[editor]
auto-completion = true
line-number = "relative"
mouse = true
bufferline = "multiple"
completion-trigger-len = 2
true-color = true
shell = ["zsh", "-c"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
F = ["select_all","select_regex"]

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
'`' = '`'
'<' = '>'

[editor.search]
smart-case = true
wrap-around = true